class AppConstants {
  AppConstants._();

  static const String appName = 'Anchor';
  static const String appTagline = 'Protecting Filipino Workers Abroad';

  // ── Countries (top OFW destinations first, then full world list A–Z) ────────
  static const List<String> countries = [
    // Home
    'Philippines',
    // Top OFW destinations
    'Saudi Arabia',
    'United Arab Emirates',
    'Qatar',
    'Kuwait',
    'Bahrain',
    'Oman',
    'Hong Kong',
    'Singapore',
    'Taiwan',
    'Japan',
    'South Korea',
    'Malaysia',
    'Canada',
    'United States',
    'United Kingdom',
    'Italy',
    'Germany',
    'Israel',
    'Jordan',
    'Lebanon',
    'Australia',
    'New Zealand',
    // Rest of the world – alphabetical
    'Afghanistan',
    'Albania',
    'Algeria',
    'Angola',
    'Argentina',
    'Armenia',
    'Austria',
    'Azerbaijan',
    'Bangladesh',
    'Belarus',
    'Belgium',
    'Benin',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Cambodia',
    'Cameroon',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Congo',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Estonia',
    'Ethiopia',
    'Finland',
    'France',
    'Gabon',
    'Georgia',
    'Ghana',
    'Greece',
    'Guatemala',
    'Guinea',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Ivory Coast',
    'Jamaica',
    'Kazakhstan',
    'Kenya',
    'Kosovo',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Libya',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Maldives',
    'Mali',
    'Malta',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Moldova',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nepal',
    'Netherlands',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Macedonia',
    'Norway',
    'Pakistan',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Poland',
    'Portugal',
    'Romania',
    'Russia',
    'Rwanda',
    'Senegal',
    'Serbia',
    'Sierra Leone',
    'Slovakia',
    'Slovenia',
    'Somalia',
    'South Africa',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Sweden',
    'Switzerland',
    'Syria',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Uganda',
    'Ukraine',
    'Uzbekistan',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
    'Other',
  ];

  // ── Organization types for verifiers ─────────────────────────────────────────
  static const List<String> organizationTypes = [
    'Government',
    'NGO',
    'Embassy',
  ];

  // ── OFW Job categories: general → specific ───────────────────────────────────
  static const Map<String, List<String>> jobCategories = {
    'Domestic & Household': [
      'Domestic Worker / Helper',
      'Caregiver (Household)',
      'Nanny / Babysitter',
      'Cook / Family Chef',
      'Housekeeper',
      'Driver',
      'Gardener',
      'Laundry Worker',
    ],
    'Healthcare & Medical': [
      'Registered Nurse',
      'Caregiver (Medical)',
      'Nursing Aide / Orderly',
      'Medical Technologist',
      'Physical Therapist',
      'Occupational Therapist',
      'Radiologic Technologist',
      'Midwife',
      'Pharmacist',
      'Dentist',
      'Doctor / Physician',
    ],
    'Construction & Engineering': [
      'Construction Laborer',
      'Electrician',
      'Plumber',
      'Welder',
      'Mason / Bricklayer',
      'Carpenter',
      'Painter',
      'Heavy Equipment Operator',
      'HVAC Technician',
      'Civil Engineer',
      'Structural Engineer',
      'Surveyor',
      'Safety Officer',
    ],
    'Hospitality & Tourism': [
      'Hotel Staff (General)',
      'Waiter / Waitress',
      'Barista',
      'Bartender',
      'Hotel Housekeeper',
      'Front Desk / Receptionist',
      'Tour Guide',
      'Casino Dealer',
      'Cruise Ship Crew',
      'Banquet / Event Staff',
      'Restaurant Manager',
    ],
    'Maritime & Seafaring': [
      'Ordinary Seaman',
      'Able Seaman',
      'Bosun',
      'Oiler / Wiper',
      'Ship Cook',
      'Marine Engineer',
      'Ship Captain / Officer',
      'Fisherman',
    ],
    'Information Technology': [
      'Software Developer / Engineer',
      'Web Developer',
      'Mobile App Developer',
      'IT Support / Help Desk',
      'Network Administrator',
      'System Administrator',
      'Data Analyst',
      'Database Administrator',
      'Cybersecurity Specialist',
      'QA Tester',
      'Graphic / UI Designer',
    ],
    'Education': [
      'Elementary Teacher',
      'Secondary / High School Teacher',
      'College Instructor',
      'Language Instructor / ESL Teacher',
      'Special Education Teacher',
      'Tutor',
      'School Administrator',
    ],
    'Manufacturing & Factory': [
      'Factory Worker (General)',
      'Machine Operator',
      'Assembly Line Worker',
      'Quality Control Inspector',
      'Forklift Operator',
      'Packer / Sorter',
      'Production Supervisor',
    ],
    'Agriculture & Farming': [
      'Farm Worker',
      'Crop Harvester',
      'Animal Caretaker / Livestock',
      'Agricultural Technician',
      'Fishery / Aquaculture Worker',
    ],
    'Security & Facilities': [
      'Security Guard',
      'Janitor / Cleaner',
      'Maintenance Technician',
      'Facility Manager',
      'Pest Control Technician',
    ],
    'Business & Finance': [
      'Accountant',
      'Bookkeeper',
      'Administrative Assistant',
      'Office Clerk',
      'Customer Service Representative',
      'Human Resources Officer',
      'Sales Representative',
      'Marketing Specialist',
    ],
    'Transportation & Logistics': [
      'Truck Driver',
      'Bus / Coach Driver',
      'Taxi / Ride-share Driver',
      'Delivery Rider',
      'Cargo Handler',
      'Warehouse Staff',
      'Logistics Coordinator',
    ],
    'Beauty & Wellness': [
      'Hair Stylist / Barber',
      'Nail Technician',
      'Massage Therapist',
      'Aesthetician / Skincare Specialist',
      'Spa Attendant',
    ],
    'Other': [
      'Other',
    ],
  };
}
