"""
Anchor monorepo scaffold — creates all empty placeholder files.
Run from repo root: python3 scripts/scaffold.py
"""
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

FILES = [
    # ── Flutter mobile ──────────────────────────────────────
    "mobile/lib/main.dart",
    "mobile/lib/firebase_options.dart",
    "mobile/lib/app.dart",
    "mobile/lib/core/constants/app_constants.dart",
    "mobile/lib/core/constants/firebase_constants.dart",
    "mobile/lib/core/services/auth_service.dart",
    "mobile/lib/core/services/firestore_service.dart",
    "mobile/lib/core/services/storage_service.dart",
    "mobile/lib/core/services/functions_service.dart",
    "mobile/lib/core/services/notification_service.dart",
    "mobile/lib/core/theme/app_theme.dart",
    "mobile/lib/core/theme/app_colors.dart",
    "mobile/lib/core/utils/validators.dart",
    "mobile/lib/core/utils/helpers.dart",
    "mobile/lib/models/user_model.dart",
    "mobile/lib/models/contract_model.dart",
    "mobile/lib/models/job_model.dart",
    "mobile/lib/models/report_model.dart",
    "mobile/lib/models/post_model.dart",
    "mobile/lib/models/alert_model.dart",
    "mobile/lib/features/auth/screens/login_screen.dart",
    "mobile/lib/features/auth/screens/register_screen.dart",
    "mobile/lib/features/auth/providers/auth_provider.dart",
    "mobile/lib/features/contracts/screens/contracts_screen.dart",
    "mobile/lib/features/contracts/screens/upload_contract_screen.dart",
    "mobile/lib/features/contracts/screens/contract_result_screen.dart",
    "mobile/lib/features/contracts/providers/contracts_provider.dart",
    "mobile/lib/features/jobs/screens/jobs_screen.dart",
    "mobile/lib/features/jobs/screens/job_detail_screen.dart",
    "mobile/lib/features/jobs/screens/report_job_screen.dart",
    "mobile/lib/features/jobs/providers/jobs_provider.dart",
    "mobile/lib/features/community/screens/feed_screen.dart",
    "mobile/lib/features/community/screens/post_detail_screen.dart",
    "mobile/lib/features/community/screens/create_post_screen.dart",
    "mobile/lib/features/community/providers/community_provider.dart",
    "mobile/lib/features/alerts/screens/alerts_screen.dart",
    "mobile/lib/features/alerts/screens/alert_detail_screen.dart",
    "mobile/lib/features/alerts/providers/alerts_provider.dart",
    "mobile/lib/features/profile/screens/profile_screen.dart",
    "mobile/lib/features/profile/screens/emergency_contacts_screen.dart",
    "mobile/lib/shared/widgets/anchor_app_bar.dart",
    "mobile/lib/shared/widgets/risk_badge.dart",
    "mobile/lib/shared/widgets/loading_overlay.dart",
    "mobile/lib/shared/widgets/empty_state.dart",
    "mobile/pubspec.yaml",
    "mobile/analysis_options.yaml",
    "mobile/README.md",
    # ── React web ────────────────────────────────────────────
    "web/index.html",
    "web/src/main.tsx",
    "web/src/App.tsx",
    "web/src/vite-env.d.ts",
    "web/src/core/config/firebase.ts",
    "web/src/core/config/routes.ts",
    "web/src/core/services/auth.service.ts",
    "web/src/core/services/firestore.service.ts",
    "web/src/core/services/storage.service.ts",
    "web/src/core/services/functions.service.ts",
    "web/src/core/context/AuthContext.tsx",
    "web/src/core/hooks/useAuth.ts",
    "web/src/core/hooks/usePagination.ts",
    "web/src/features/auth/components/LoginForm.tsx",
    "web/src/features/auth/components/ProtectedRoute.tsx",
    "web/src/features/auth/hooks/useLogin.ts",
    "web/src/features/dashboard/DashboardPage.tsx",
    "web/src/features/dashboard/StatsCard.tsx",
    "web/src/features/dashboard/RiskChart.tsx",
    "web/src/features/jobs/components/JobsTable.tsx",
    "web/src/features/jobs/components/JobDetailPanel.tsx",
    "web/src/features/jobs/components/VerifyJobModal.tsx",
    "web/src/features/jobs/hooks/useJobs.ts",
    "web/src/features/contracts/components/ContractsTable.tsx",
    "web/src/features/contracts/components/ContractDetailPanel.tsx",
    "web/src/features/contracts/components/RiskFlagsView.tsx",
    "web/src/features/contracts/hooks/useContracts.ts",
    "web/src/features/reports/components/ReportsTable.tsx",
    "web/src/features/reports/components/ReportDetailPanel.tsx",
    "web/src/features/reports/hooks/useReports.ts",
    "web/src/features/community/components/PostsTable.tsx",
    "web/src/features/community/components/FlaggedPostsQueue.tsx",
    "web/src/features/community/hooks/useCommunity.ts",
    "web/src/features/alerts/components/AlertsTable.tsx",
    "web/src/features/alerts/components/CreateAlertModal.tsx",
    "web/src/features/alerts/hooks/useAlerts.ts",
    "web/src/features/analytics/AnalyticsPage.tsx",
    "web/src/features/analytics/CountryHeatmap.tsx",
    "web/src/components/ui/RiskBadge.tsx",
    "web/src/components/ui/StatusBadge.tsx",
    "web/src/components/ui/DataTable.tsx",
    "web/src/components/ui/Modal.tsx",
    "web/src/components/ui/Button.tsx",
    "web/src/components/ui/Input.tsx",
    "web/src/components/layout/Sidebar.tsx",
    "web/src/components/layout/TopBar.tsx",
    "web/src/components/layout/DashboardLayout.tsx",
    "web/src/pages/LoginPage.tsx",
    "web/src/pages/DashboardPage.tsx",
    "web/src/pages/JobsPage.tsx",
    "web/src/pages/ContractsPage.tsx",
    "web/src/pages/ReportsPage.tsx",
    "web/src/pages/CommunityPage.tsx",
    "web/src/pages/AlertsPage.tsx",
    "web/src/pages/AnalyticsPage.tsx",
    "web/src/pages/NotFoundPage.tsx",
    "web/src/types/index.ts",
    "web/src/utils/formatters.ts",
    "web/src/utils/validators.ts",
    "web/package.json",
    "web/tsconfig.json",
    "web/tsconfig.node.json",
    "web/vite.config.ts",
    "web/tailwind.config.ts",
    "web/postcss.config.js",
    "web/README.md",
    # ── Firebase ─────────────────────────────────────────────
    "firebase/functions/src/index.ts",
    "firebase/functions/src/analyzeContract.ts",
    "firebase/functions/src/verifyJob.ts",
    "firebase/functions/src/generateSafetyAlert.ts",
    "firebase/functions/src/notifications.ts",
    "firebase/functions/src/aiService.ts",
    "firebase/functions/package.json",
    "firebase/functions/tsconfig.json",
    "firebase/rules/firestore.rules",
    "firebase/rules/storage.rules",
    "firebase/rules/firestore.indexes.json",
    # ── AI services ──────────────────────────────────────────
    "ai-services/README.md",
    # ── Docs ─────────────────────────────────────────────────
    "docs/architecture.md",
    "docs/api.md",
]

created = skipped = 0
for rel in FILES:
    full = os.path.join(BASE, rel)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    if not os.path.exists(full):
        open(full, "w").close()
        print(f"  + {rel}")
        created += 1
    else:
        skipped += 1

print(f"\n✅  {created} files created, {skipped} already existed.")
